const PAYMENT_METHOD_CASH = 'Dinheiro'
const PAYMENT_METHOD_CREDIT= 'Cartão de Crédito'
const PAYMENT_METHOD_DEBIT = 'Cartão de Débito'


export { PAYMENT_METHOD_CASH, PAYMENT_METHOD_CREDIT, PAYMENT_METHOD_DEBIT }